### ISSUE TITLE
Lightbulb menu doesn't show conversion actions

### ISSUE THREAD

**Issue by enstulen** [wix/vscode-glean#113]
I want to convert a class component to a functional component, but the option doesn't show up in the lightbulb menu. 

I downloaded a fresh copy of VsCode so it wouldn't interfere with other extensions, and same thing happens. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7783861/82752232-e1725380-9dbc-11ea-8663-6da10f4cd61d.gif)

**Comment by borislit** [comment]
@Hey @enstulen ! Thanks for the issue!
I think this has to do with the fact that u are selecting the whole file content. Try selecting JUST the  component (without the import and export).

**Comment by enstulen** [comment]
Thanks for the commen! In the GIF, you see that I first select JUST the component, then I try selected everything else too.

**Comment by borislit** [comment]
Gocha! I'll have a look at it asap!

**Comment by borislit** [comment]
Hi @enstulen so I found the issue. Will release the fix tomorrow

**Comment by borislit** [comment]
Hey @enstulen ! Check out the new version with the fix

**Comment by enstulen** [comment]
Awesome, thanks!
