### ISSUE TITLE
Why can't I export this component?

### ISSUE THREAD

**Issue by njoppi2** [wix/vscode-glean#120]
![Screenshot from 2020-09-26 12-59-00](https://user-images.githubusercontent.com/16853682/94344815-47374c00-fff8-11ea-976c-fcf1e9db82dd.png)

For some weird reason the options to extract this component ↑ don't show up when I click the light bulb.
However, if I select this component ↓, then the option shows up, why is that?

![Screenshot from 2020-09-26 13-02-10](https://user-images.githubusercontent.com/16853682/94344849-8f566e80-fff8-11ea-9d8b-98489e8874b9.png)

**Comment by borislit** [comment]
@njoppi2 thanks for the issue! Sorry for late response. Been away for a while. Can you pls paste the code snippet that causes the issues?

**Comment by njoppi2** [comment]
No problem, just to clarify a little more, the only options that appear to me when I select this text is "Extract to constant in enclosing scope" and "Extract to function in module scope"
Here's the select text that didn't work: 
<PriceEditingContainer>
            <ButtonContainer>
              <Button kind="available" onClick={() => exportConnectorsPrice(user?.authToken)} visual="secondary" grayBorder={true} textSize={12}><DownArrow />Download da planilha</Button>
            </ButtonContainer>
            <ButtonContainer>
              <Button kind="available" visual="primary" onClick={() => {}} grayBorder textSize={12}>
                <UpArrow />Upload da planilha
                <HiddenInput
                  onChange={({ target: { validity, files } }) =>
                    validity.valid && files && setSheetFile(files[0])
                  }
                />
              </Button>
            </ButtonContainer>
          </PriceEditingContainer>

**Comment by lauridskern** [comment]
I have the same issue
