### ISSUE TITLE
SFC is deprecated in @types/react

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wix/vscode-glean#121]
Hi, thanks for this really useful extension! From the `@deprecated` tag on `React.SFC`:

> ```
> @deprecated
> as of recent React versions, function components can no longer be considered 'stateless'.
> Please use FunctionComponent instead.
> ```

Personally, I've found `FC` used as `React.FC` to be a more succinct form. Would you accept a PR changing the import?

**Comment by borislit** [comment]
@JoshuaKGoldberg hey! The new version (just released) auto detects the version of react you are using, and will use FC for newer version. Tell me if the issue is resolved for you

**Comment by JoshuaKGoldberg** [comment]
Perfect :) thanks!
