### ISSUE TITLE
Please explain what "VSCode debug sidebar" is?

### ISSUE THREAD

**Issue by 19007361** [wix/vscode-glean#128]
I cannot run the extension (it's in my extension list) on an established React app.

**Comment by 19007361** [comment]
Your gifs are misleading because they never show you have to click the lightbulb to make it work

**Comment by bogdan-calapod** [comment]
THAT'S WHAT YOU HAVE TO DO TO TRIGGER IT ?!

I swear, just this:

> you have to click the lightbulb to make it work

Somewhere, anywhere in the readme would have been a big helper!
