### ISSUE TITLE
Can't find this extension in VS Code

### ISSUE THREAD

**Issue by JoshMcCullough** [wix/vscode-glean#155]
I'm running VS Code 1.64.2 on Manjaro and I can't find this extension in the Marketplace, nor can I install it via `Ctrl+P`, `ext install wix.glean <enter>` -- thoughts?

**Comment by filiptronicek** [comment]
Hey there, @JoshMcCullough, are you using the official bundles distributed by Microsoft and not by chance using [VS Codium](https://vscodium.com/)?

**Comment by JoshMcCullough** [comment]
Yes, official OSS version.

![image](https://user-images.githubusercontent.com/4859660/167268617-b31bd7ee-3294-4d69-a17b-ef38ea21a91d.png)

**Comment by filiptronicek** [comment]
@JoshMcCullough I am not sure with what marketplace the OSS version gets bundled with - I would guess none. Can you install / find any other extensions? 

You may be using https://open-vsx.org/ where this extension is not yet published.

**Comment by JoshMcCullough** [comment]
Yep, I replaced the `code` package (from AUR) with the official `visual-studio-code-bin`, instead: https://aur.archlinux.org/packages/visual-studio-code-bin

Found it now. Thanks.
