### ISSUE TITLE
Using Hooks to replace setState calls

### ISSUE THREAD

**Issue by borislit** [wix/vscode-glean#27]
Today, when class components is refactored to the functional component, all setState calls are lost, as there was no equivalent concept. Today, after Hooks have been introduced, they seem to be just that.
It would be awesome to explore such a possibility. 
This should be an opt-in feature (using configuration)

**Comment by itzsaga** [comment]
When should this be explored? Hooks are still an early stage proposal and I think Dan said it best in this tweet https://twitter.com/dan_abramov/status/1057027428827193344

**Comment by borislit** [comment]
@itzsaga I agree, and for this very reason what i was thinking was to have it as an "opt in" feature which you would turn on through a config parameter. Also, that also means that the code for that feature would have to be isolated.
