### ISSUE TITLE
Error for simple component conversion

### ISSUE THREAD

**Issue by OliverJAsh** [wix/vscode-glean#51]
> Property value expected type of string but got null

TS 3.1.6
VS Code 1.30.2
Extension version 4.2.3

``` tsx
import React, { Component } from 'react';

class App extends Component<{}> {
  render() {
    return (
      <div />
    );
  }
}

```

![image](https://user-images.githubusercontent.com/921609/50904751-090b8a80-1419-11e9-96e2-3558657cc6ed.png)

**Comment by borislit** [comment]
Hey @OliverJAsh ! Thanks for the report. Ill check it out right away. Keep in mind, currently, there is an issue in publishing a new version to the market.

**Comment by ecbrodie** [comment]
@borislit I also got this error when doing a simple conversion, although for me it was the other way around. It was in a `.tsx` file, so not sure if Typescript is causing an issue here. Here's some code to try to reproduce the issue, via converting from a stateless to a stateful component (with all code from `export default function Test` to the end of the file highlighted):

```
import React from "react"

type Props = {
  foo: string
}

export default function Test({ foo = "bar" }: Props) {
  return <div>Foo = {foo}</div>
}
```

My workspace:

* VSCode 1.31.1
* vscode-glean 4.6.0
* MacOS 10.14.3

**Comment by borislit** [comment]
Hey @ecbrodie ! Ill give it another go later today and keep you posted! Thanks for reporting!

**Comment by borislit** [comment]
@ecbrodie i found the issue. It has to do with incorrect handling of default prop values. Im working on a fix. meanwhile, if u remove the `= "bar"` it'll work

**Comment by borislit** [comment]
@ecbrodie https://github.com/wix/vscode-glean/commit/3cf1c6589359902988566ac2fa8cc74dc6fd3881 should fix the issue. It also adds support for `defaultProps`. Tell me how it goes. Thanks

**Comment by ecbrodie** [comment]
@borislit I just checked the latest version of Glean and it now works without error when there are default prop values. Thank you for the quick turnaround.

Also, I checked the example from the OP (@OliverJAsh) and that conversion also works without error. Thus, with default props, I have confirmed that stateful-to-stateless and stateless-to-stateful conversions are working just fine. I think this issue can be closed.

**Comment by borislit** [comment]
Thanks @ecbrodie ! Glad to help!

**Comment by OliverJAsh** [comment]
I'm still running into this error, using 5.0.1.

<img width="1025" alt="Screenshot 2020-06-08 at 14 54 20" src="https://user-images.githubusercontent.com/921609/84038504-f099f980-a997-11ea-92f2-973ddf8d1e3d.png">

I also get the same error when I try "wrap with `useMemo`":

<img width="1025" alt="Screenshot 2020-06-08 at 14 55 21" src="https://user-images.githubusercontent.com/921609/84038638-16bf9980-a998-11ea-869f-ceb7b805957b.png">

And "wrap with `useEffect`" produces a lot of weird code. Input:

```tsx
import * as React from 'react';

const App = () => {
    Math.random();
    return <div />;
};
```

Output:

```tsx
import * as React from 'react';

const App = () => {
    var __signature__ = typeof reactHotLoaderGlobal !== 'undefined' ? reactHotLoaderGlobal.default.signature : function (a) {
  return a;
};

React.useEffect(() => {
  () => {
    Math.random();
  };
});
    return <div />;
};
```

**Comment by borislit** [comment]
Hey @OliverJAsh ! Thanks for the report. Will have a look ASAP

**Comment by techsin** [comment]
Also it shows up in non react code everywhere.
