### ISSUE TITLE
Please disable the extension for plain text files

### ISSUE THREAD

**Issue by rbadapanda** [wix/vscode-glean#69]

**Comment by borislit** [comment]
@rbadapanda I agree. This was done intentionally a while back, but is not longer relevant.
Care for a PR? Should be an easy fix
You need to change the activation event here: https://github.com/wix/vscode-glean/blob/master/package.json#L21
We should use `onLanguage` activation event (https://code.visualstudio.com/api/references/activation-events#onLanguage) listing the relevant language(javascript, javascript react, typescript, typescript react)

**Comment by rbadapanda** [comment]
@borislit I created a PR for the same.

Thanks

**Comment by borislit** [comment]
@rbadapanda merged! Thanks!
