### ISSUE TITLE
cannot convert stateful component to hooks one

### ISSUE THREAD

**Issue by RamyEl-basyouni** [wix/vscode-glean#75]
Hi,
I tried to use your experiential feature to convert class code base to hooks.
As you explained, i tried to edit the settings file in VSCode located in 
**Users/User_name/Library/Application Support/Code/User/settings.json**
with this JSON
{
```
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "terminal.integrated.rendererType": "dom",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "glean.experiments": {
        "type": "hooksForFunctionalComponents"
    }
}
```
but always cannot find the option to convert stateful component to hook.

**Comment by borislit** [comment]
Hey @RamyEl-basyouni . Your configuration seems to be incorrect. As you can see in the docs,
`glean.experiments` is an array of strings. https://github.com/wix/vscode-glean#gleanexperiments-default-

Hence, it should look as follows: `"glean.experiments": ["hooksForFunctionalComponents"]`

**Comment by jobokai** [comment]
![image](https://user-images.githubusercontent.com/13200689/62493780-f2a39280-b79f-11e9-99ce-2030cf6d3049.png)
I'm having a similar issue and notice this error message when editing the settings.json file. Doing a few conversions it then seems to have a pathing bug: 
![image](https://user-images.githubusercontent.com/13200689/62493882-2bdc0280-b7a0-11e9-81bd-ebba308f7c14.png)

Removing the setting then makes everything work again.

**Comment by borislit** [comment]
@jakutis, IMO You can ignore the formatting error. Can you please post the code snippet You are trying to refactor?  Also, which OS are u using? Windows?

**Comment by jobokai** [comment]
```
class Copyright extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (<div className='copyright'>
        <span className="purdue-logo"></span>
        <div className="copyright-statement">
          © {moment().format("YYYY")} .<br />
          text here.
        </div>
      </div>);
  }
}
export default Copyright;
```

I'm on a windows machine. Just wanting to test things out, it looks really interesting!

**Comment by borislit** [comment]
@jobokai This indeed looks like a bug, caused by the last release. Working on the fix now :) Ill keep you posted

**Comment by borislit** [comment]
@jobokai @RamyEl-basyouni I've just published a new version that should include a fix. Please validate

**Comment by jobokai** [comment]
I’ll take a look here tonight when I get home from work! Thanks for checking on things

**Comment by RamyEl-basyouni** [comment]
Hi @borislit ,

First, i have upgraded to the latest version of glean@4.15.1
I tried to update my **settings.json** file as advised 
<img width="552" alt="Screen Shot 2019-08-06 at 10 08 03 AM" src="https://user-images.githubusercontent.com/8338424/62522688-7ad27800-b832-11e9-8a7d-eda0dae89fe5.png">

But i always cannot find the option of **convert stateful to stateless component**

Here is the screenshot of the options that is available on my codebase
<img width="457" alt="Screen Shot 2019-08-06 at 10 21 09 AM" src="https://user-images.githubusercontent.com/8338424/62523629-7f982b80-b834-11e9-87b7-16767d9972dc.png">


FYI, here is my code that i am trying to convert it to hook.
https://gist.github.com/RamyEl-basyouni/fb6fe324c71e5b2cab15fb212f127201

**Comment by jobokai** [comment]
@borislit I'm also noticing the same thing that @RamyEl-basyouni described.

**Comment by jobokai** [comment]
I hopped over to my mac setup to see if it was an operating system issue. I had this class that I wrote:
![example2](https://user-images.githubusercontent.com/13200689/62550501-5a0d2100-b838-11e9-93fa-d8d5a2c43fac.png)

When I try to convert it to hooks, I have no options to convert it. I have things turned on in my settings.json.
![example1](https://user-images.githubusercontent.com/13200689/62550507-5b3e4e00-b838-11e9-81e3-b71d6c3ac8e5.png)

**Comment by borislit** [comment]
@RamyEl-basyouni I've just checked the gist you've posted and it worked for me. Are you selecting JUST the component or the contents of the whole file?

**Comment by borislit** [comment]
@RamyEl-basyouni Also, in order to get a more better result, before applying the refactoring, I suggest you change all the instance variables i.e `this.foo` to state variables i.e `this.state.foo`. Besides this being more correct in terms of React, this will produce a more accurate transformation.

**Comment by RamyEl-basyouni** [comment]
@borislit , ok it is working now, regarding your mention to 
> change all the instance variables i.e this.foo to state variables i.e this.state.foo. 
i think it will not be perfect to convert instance variables to state variables as the instance variables prevent component from rerendering component which will badly effects performance.

**Comment by 2012mjm** [comment]
> Hi @borislit ,
> 
> First, i have upgraded to the latest version of glean@4.15.1
> I tried to update my **settings.json** file as advised
> <img alt="Screen Shot 2019-08-06 at 10 08 03 AM" width="552" src="https://user-images.githubusercontent.com/8338424/62522688-7ad27800-b832-11e9-8a7d-eda0dae89fe5.png">
> 
> But i always cannot find the option of **convert stateful to stateless component**
> 
> Here is the screenshot of the options that is available on my codebase
> <img alt="Screen Shot 2019-08-06 at 10 21 09 AM" width="457" src="https://user-images.githubusercontent.com/8338424/62523629-7f982b80-b834-11e9-87b7-16767d9972dc.png">
> 
> FYI, here is my code that i am trying to convert it to hook.
> https://gist.github.com/RamyEl-basyouni/fb6fe324c71e5b2cab15fb212f127201

Fix your problem:
https://github.com/wix/vscode-glean/pull/78

**Comment by borislit** [comment]
Merged @2012mjm ! Thanks for the PR!

**Comment by M-Izadmehr** [comment]
@borislit 
The settings schema expects glean.experiments to be `string` instead of `array`. I created a small MR #82 which solves this issue.
