### ISSUE TITLE
class instance variables is not to converted to its equivalent useRef in hooks

### ISSUE THREAD

**Issue by RamyEl-basyouni** [wix/vscode-glean#77]
while converting stateful component to hook, instances variables in class is not coverted to its equivalent in hooks which is useRef().
https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variablesso any code with syntax:
`this.sView`
should be:
`const sView = useRef()`

**Comment by borislit** [comment]
I agree @RamyEl-basyouni . I've been pondering about this myself. Care for a PR? I'd love to point you in the right direction?

**Comment by borislit** [comment]
Hey @RamyEl-basyouni! I've just released a new version that supports `useRef`. I'd love for some feedback
