### ISSUE TITLE
Error message clarification: 'You must pass a scope and parentPath'

### ISSUE THREAD

**Issue by DaveClissold** [wix/vscode-glean#95]
Hi I am getting the following error when trying to convert a react PureComponent to stateless.  
```
You must pass a scope and parentPath unless traversing a Program/File. Instead of that you tried to traverse a Identifier node without passing scope and parentPath.
```
Sorry if this is not the right place, but I am confused and cannot find an answer anywhere.

**Comment by borislit** [comment]
@DaveClissold Hey! Can you pls post the snippet you are trying to refactor?

**Comment by Arelav** [comment]
I can't put  a production code here however when I try to convert class component to functional it works fine until I put 
```
  "glean.experiments": [
    "hooksForFunctionalComponents"
  ],
```
in VSCode settings.

**Comment by borislit** [comment]
@Arelav. Thanks for reporting. Can you try to create a minimal usecase?

**Comment by Arelav** [comment]
> @Arelav. Thanks for reporting. Can you try to create a minimal usecase?

So the minimal example does work without experiment and doesn't when experiment is on.
```
import React from 'react';

interface Props {
  text: string;
}

class MyComponent extends React.PureComponent<Props> {
  render() {
    const { text } = this.props;

    return <>Test {text}</>;
  }
}

export default MyComponent;
```
Looks like props distructuring is an issue here.

Because this works fine in both cases.
```
class MyComponent extends React.PureComponent<Props> {
  render() {
    return <>Test {this.props.text}</>;
  }
}
```

**Comment by bobbyrenwick** [comment]
Seems like there's the same issue whenever you try to spread `this.props` in JSX too:

```ts
class MyComponent extends React.PureComponent<Record<string, unknown>, {}> {
    render() {
        return (
            <OtherComponent {...this.props} />
        );
    }
}
```

gives the same error

**Comment by borislit** [comment]
Hey guys! Thanks for reporting! Im on it!

**Comment by borislit** [comment]
Hey guys. Check out the new release.  It should fix both the issues you've encountered. Pls confirm. Thanks

**Comment by bobbyrenwick** [comment]
Hi @borislit, I just updated and it fixed the issue. Thanks :+1: I spend so much time moving from old, class based components to functional ones and this is really helping to speed things up!

**Comment by borislit** [comment]
@bobbyrenwick Super glad to hear that! If you have suggestion on how we can better the extension in order to make it even more useful to you - I'd love to hear your suggestions :)

**Comment by omaryoussef** [comment]
Hello! I'm using 5.1.1 and I still see the issue when trying to refactor this:

```
type Props = { content: Content };

export default class BannerItem extends React.PureComponent<Props> {
  contentDidSelect = () => {
    NavigationService.navigateToContent(this.props.content);
  };

  render() {
    return (
      <TouchableOpacity
        activeOpacity={1}
        style={styles.slideInnerContainer}
        onPress={this.contentDidSelect}>
        <View style={[styles.imageContainer, mainStyles.imageContainerShadow]}>
          <Image
            source={{ uri: this.props.content.image.en }}
            style={styles.image}
          />
        </View>
      </TouchableOpacity>
    );
  }
}
```

**Comment by danielo515** [comment]
I'm also facing this problem, and it's a pity because I have a bunch of components to transform.
If you are using regular codemods I may take a look if you link it

**Comment by borislit** [comment]
Hey @danielo515 , ill have a renewed view on the issue ASAP.
I would like to get another snippet that causes the error

**Comment by borislit** [comment]
@omaryoussef the issue seems to be with function assignment. Once i've removed it - it works. Im working on the fix

**Comment by borislit** [comment]
@omaryoussef  @danielo515 I've just released a new version with the fix. Can you please verify?

**Comment by omaryoussef** [comment]
@borislit Can confirm the issue was fixed, thank you so much! 🎉

**Comment by danielo515** [comment]
I confirm this particular bug was fixed on 5.2.2

**Comment by sirajalam049** [comment]
I have 5.2.2 installed, still getting the error :(

**Comment by borislit** [comment]
@sirajalam049 can you pls provide a code snippet?

**Comment by ghost** [comment]
I am also getting this error with 5.2.2. You can try it with this repo on the App.js file.
[https://github.com/DevExpress-Examples/DataGrid-How-to-hide-disable-Edit-Form-items-based-on-another-item-s-value](https://github.com/DevExpress-Examples/DataGrid-How-to-hide-disable-Edit-Form-items-based-on-another-item-s-value)
